#!/usr/bin/env bash

## Post recieve git hook
## - - - - - - - - - - -
# This hook requires core.worktree to be explicitly set, and
# receive.denyCurrentBranch to be set to false.

# Read standard input or hook will fail
while read oldrev newrev refname
do
:
done

# Unset GIT_DIR or the universe will implode
unset GIT_DIR

# Change directory to the working tree; exit on failure
cd `git config --get core.worktree` || exit

# Force checkout
git checkout --force

# Force update submodules
git submodule update --init --recursive --force
