#!/usr/bin/env bash

## Post recieve git hook
## - - - - - - - - - - -

# Standard post-recv behaviour.
while read oldrev newrev refname
do
:
done

# Map working dir to global
export GIT_DIR=$(pwd);

# CD to repo
cd $DOTFILES || exit;

# Prepare repo
git checkout --force
git submodule update --init --recursive --force
