#!/usr/bin/env bash

cd $HOME/dotfiles;
. lib/control.sh
. lib/git.sh

# Auto push on commit
BRANCH=$(GetBranch);
echo "Auto-commit hook engaged. Pushing to github repository.";
echo " using branch :: ${BRANCH}";

git push origin $BRANCH;

echo "Pushed to github.";
Pause;
