# Add to PATH
export PATH=$PATH:"$HOME/.cabal/bin":"$HOME/emscripten"

# dircolors
eval `dircolors ~/.dir_colors`

# Set vimpath
#export VIM="$HOME/dotfiles/link/vim";

# Git
#alias add="git add"
#alias ci ="git commit"
#
#function GitACP () {
#  git add $@;
#  git commit -a;
#}

#function pi() { sudo aptitude install $@; }

function pkg.search  () { export SEARCH="$@"; sudo aptitude search $SEARCH; }
function pkg.install () {
  INST=${@:-SEARCH};
  echo "Installing ${INST}."
  sudo aptitude install $INST;
}
