# Add to PATH
export PATH=$PATH:"$HOME/.cabal/bin":"$HOME/emscripten"

# dircolors
eval `dircolors ~/.dir_colors`

# Set vimpath
#export VIM="$HOME/dotfiles/link/vim";

# Git
#alias add="git add"
#alias ci ="git commit"
#
#function GitACP () {
#  git add $@;
#  git commit -a;
#}

#function pi() { sudo aptitude install $@; }
