# Add to PATH
export PATH="$PATH:$HOME/.cabal/bin:/usr/local/aws/eb/bin:/usr/local/aws/rds/bin:/usr/local/aws/elasticbeanstalk/eb/linux/python2.7:/usr/local/aws/elasticbeanstalk/AWSDevTools/Linux"

# Set vimpath
#export VIM="$HOME/dotfiles/link/vim";

# Git
#alias add="git add"
#alias ci ="git commit"
#
#function GitACP () {
#  git add $@;
#  git commit -a;
#}

